server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /opt/dns-blocked-page/public;
    index index.html;

    server_tokens off;
    autoindex off;

    location / {
        try_files /index.html =404;
    }
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;

    root /opt/dns-blocked-page/public;
    index index.html;

    server_tokens off;
    autoindex off;

    ssl_certificate /etc/letsencrypt/live/rpz.trevizamnetwork.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rpz.trevizamnetwork.com.br/privkey.pem;

    location / {
        try_files /index.html =404;
    }
}
