expose_php=Off
memory_limit=256M
max_execution_time=180
upload_max_filesize=24M
post_max_size=26M
opcache.enable=1
opcache.validate_timestamps=0
opcache.memory_consumption=128
log_errors=On
error_log=/proc/self/fd/2
