@extends('layouts.app')
@section('title', $group->name)
@section('content')
@php($statusLabels = ['partial' => 'Parcial', 'listed' => 'Listado', 'clean' => 'Limpo', 'error' => 'Erro', 'timeout' => 'Erro', 'skipped' => 'Ignorado', 'unchecked' => 'Não verificado'])
<div class="rbl-dashboard">
<div class="page-heading"><h1>{{ $group->name }}</h1><a class="button" href="{{ route('rbl.groups.edit',$group) }}">Editar grupo</a></div>
@include('rbl.navigation')
<div class="panel"><p>{{ $group->category ?? 'Sem categoria' }} @if($group->category === 'cgnat')<span class="status-pill is-info">CGNAT</span>@endif · {{ $group->enabled ? 'Ativo' : 'Desativado' }}</p><p>{{ $group->description }}</p><p>Total de alvos: {{ $total }} · Listados agora: {{ $listed }} · Eventos abertos: {{ $open }}</p><p>Último check: {{ $lastCheck?->checked_at?->format('d/m/Y H:i:s') ?? 'Nunca' }} · Execução: {{ $lastCheck?->rbl_run_id ?? '—' }}</p><form method="POST" action="{{ route('rbl.groups.toggle',$group) }}">@csrf @method('PATCH')<button class="button">{{ $group->enabled ? 'Desativar' : 'Ativar' }}</button></form></div>
<div class="panel"><h2>Resumo dos blocos CGNAT</h2><div class="rbl-scan-grid"><div><span>Blocos CIDR</span><strong>{{ $scanSummary['blocks'] }}</strong></div><div><span>Total de IPs monitorados</span><strong>{{ $scanSummary['total_ips'] }}</strong></div><div><span>Verificados no ciclo</span><strong>{{ $scanSummary['scanned_ips'] }}</strong></div><div><span>Pendentes estimados</span><strong>{{ $scanSummary['pending_ips'] }}</strong></div><div><span>IPs listados</span><strong>{{ $scanSummary['listed_ips'] }}</strong></div><div><span>IPs com erro</span><strong>{{ $scanSummary['error_ips'] }}</strong></div></div><div class="rbl-progress-label"><strong>Progresso agregado ponderado</strong><span>{{ number_format($scanSummary['progress'], 1, ',', '.') }}%</span></div><div class="rbl-progress" role="progressbar" aria-label="Progresso agregado dos blocos" aria-valuemin="0" aria-valuemax="100" aria-valuenow="{{ $scanSummary['progress'] }}"><span style="width: {{ $scanSummary['progress'] }}%"></span></div></div>
<div class="panel"><h2>Alvos do grupo</h2><div class="table-responsive"><table class="data-table"><thead><tr><th>Alvo</th><th>Valor monitorado</th><th>Status</th><th>Progresso do bloco</th><th>Último check</th></tr></thead><tbody>@forelse($targets as $target)<tr><td><a href="{{ route('rbl.targets.show',$target) }}">{{ $target->name }}</a></td><td>{{ $target->value }}</td><td>{{ $statusLabels[$target->last_status ?? 'unchecked'] ?? $target->last_status }}</td><td>@if($target->type === 'cidr'){{ $target->scanState?->scanned_ips ?? 0 }}/{{ $target->scanState?->total_ips ?? $target->cidrTotalIps() }} ({{ $target->scanState?->progressPercent() ?? 0 }}%) · pendentes {{ $target->scanState?->pendingIps() ?? $target->cidrTotalIps() }} · listados {{ $target->scanState?->listed_ips ?? 0 }} · erros {{ $target->scanState?->error_ips ?? 0 }}@else—@endif</td><td>{{ $target->last_checked_at?->format('d/m/Y H:i:s') ?? 'Nunca' }}</td></tr>@empty<tr><td colspan="5">Nenhum alvo associado.</td></tr>@endforelse</tbody></table></div>{{ $targets->links() }}</div>
<div class="panel"><h2>Últimos eventos do grupo</h2>@include('rbl.event-table')</div>
</div>
@endsection
