<div class="panel">
<h2>Delist assistido</h2><p>Este painel apenas orienta e registra ações manuais. O evento só é resolvido quando um check DNSBL posterior voltar clean.</p>
<div class="table-responsive"><table class="data-table"><tbody><tr><th>RBL/lista</th><td>{{ $event->list?->name ?? '—' }}</td><th>IP afetado</th><td>{{ $event->last_checked_value ?? '—' }}</td></tr><tr><th>Valor monitorado</th><td>{{ $event->target?->value ?? '—' }}</td><th>Grupo</th><td>{{ $event->target?->group?->name ?? '—' }}</td></tr><tr><th>Status técnico</th><td>{{ $event->status }}</td><th>Status atual do delist</th><td>{{ $event->latestDelistRequest?->statusLabel() ?? 'Não solicitado' }}</td></tr></tbody></table></div>
@if($event->list?->lookup_url)<p><a class="button button-small" href="{{ $event->list->lookup_url }}" target="_blank" rel="noopener noreferrer">Abrir consulta oficial</a></p>@endif
@if($event->list?->delist_url)<p><a class="button button-small" href="{{ $event->list->delist_url }}" target="_blank" rel="noopener noreferrer">Abrir solicitação oficial</a></p>@endif
@if($event->list?->delist_instructions)<h3>Orientação da lista</h3><p>{!! nl2br(e($event->list->delist_instructions)) !!}</p>@else<p>Nenhuma orientação cadastrada para esta lista. Revise o fluxo oficial antes de agir.</p>@endif
<div class="field-group"><label for="suggested_delist_text">Texto sugerido para editar e copiar</label><textarea class="form-control" id="suggested_delist_text" rows="12">{{ $suggestedDelistText }}</textarea></div>
<h3>Registrar ação manual</h3><div class="form-actions">@foreach(['instructions_viewed' => 'Marcar instruções como visualizadas', 'requested' => 'Marcar como solicitado', 'waiting' => 'Marcar como aguardando', 'accepted' => 'Marcar como aceito', 'rejected' => 'Marcar como rejeitado', 'not_applicable' => 'Marcar como não aplicável'] as $status => $label)<form method="POST" action="{{ route('rbl.events.delist.store', $event) }}">@csrf<input type="hidden" name="status" value="{{ $status }}"><button class="button button-small" type="submit">{{ $label }}</button></form>@endforeach</div>
@if($event->latestDelistRequest)<h3>Atualizar registro atual</h3><form method="POST" action="{{ route('rbl.events.delist.update', [$event, $event->latestDelistRequest]) }}">@csrf @method('PATCH')<div class="form-grid">
<div class="field-group"><label for="delist_status">Status</label><select class="form-control" id="delist_status" name="status">@foreach(\App\Models\RblDelistRequest::STATUS_LABELS as $value => $label)<option value="{{ $value }}" @selected(old('status', $event->latestDelistRequest->status) === $value)>{{ $label }}</option>@endforeach</select></div>
<div class="field-group"><label for="requested_at">Data da solicitação</label><input class="form-control" id="requested_at" name="requested_at" type="datetime-local" value="{{ old('requested_at', $event->latestDelistRequest->requested_at?->format('Y-m-d\TH:i')) }}"></div>
<div class="field-group"><label for="request_url">URL usada/registrada</label><input class="form-control" id="request_url" name="request_url" type="url" maxlength="2048" value="{{ old('request_url', $event->latestDelistRequest->request_url) }}"></div>
<div class="field-group"><label for="protocol">Protocolo</label><input class="form-control" id="protocol" name="protocol" maxlength="255" value="{{ old('protocol', $event->latestDelistRequest->protocol) }}"></div>
<div class="field-group"><label for="contact_email">E-mail de contato</label><input class="form-control" id="contact_email" name="contact_email" type="email" maxlength="255" value="{{ old('contact_email', $event->latestDelistRequest->contact_email) }}"></div>
<div class="field-group"><label for="delist_notes">Observações</label><textarea class="form-control" id="delist_notes" name="notes" maxlength="5000" rows="4">{{ old('notes', $event->latestDelistRequest->notes) }}</textarea></div></div><button class="button button-primary" type="submit">Atualizar protocolo/URL/observação</button></form>@endif
<h3>Histórico de delist</h3><div class="table-responsive"><table class="data-table"><thead><tr><th>Registro</th><th>Status</th><th>Solicitado em</th><th>Protocolo / URL</th><th>Responsável</th><th>Observação</th></tr></thead><tbody>@forelse($event->delistRequests as $item)<tr><td>{{ $item->created_at?->format('d/m/Y H:i:s') }}</td><td>{{ $item->statusLabel() }}</td><td>{{ $item->requested_at?->format('d/m/Y H:i:s') ?? '—' }}</td><td>{{ $item->protocol ?? '—' }} @if($item->request_url)<a href="{{ $item->request_url }}" target="_blank" rel="noopener noreferrer">Abrir</a>@endif</td><td>{{ $item->user?->name ?? 'usuário removido' }}</td><td>{!! nl2br(e($item->notes ?? '—')) !!}</td></tr>@empty<tr><td colspan="6">Nenhuma ação de delist registrada.</td></tr>@endforelse</tbody></table></div>
</div>
