@extends('layouts.app')
@section('title', 'Evento RBL #'.$event->id)
@section('content')
<div class="page-heading"><div><div class="page-eyebrow">Investigação operacional</div><h1>Evento RBL #{{ $event->id }}</h1><p>Classificações operacionais não alteram o estado técnico da blacklist.</p></div><div><a class="button" href="{{ route('rbl.events.report', $event) }}" target="_blank" rel="noopener">Relatório imprimível</a></div></div>
@include('rbl.navigation')
<div class="panel"><h2>Dados do evento</h2><div class="table-responsive"><table class="data-table"><tbody>
<tr><th>Status técnico</th><td>{{ $event->status }}</td><th>Investigação</th><td>{{ ['pending' => 'Pendente', 'investigating' => 'Em investigação', 'investigated' => 'Investigado', 'false_positive' => 'Falso positivo'][$event->investigation_status] ?? 'Sem classificação' }}</td></tr>
<tr><th>Alvo</th><td>{{ $event->target?->name ?? '—' }}</td><th>Valor monitorado</th><td>{{ $event->target?->value ?? '—' }}</td></tr>
<tr><th>Grupo</th><td>{{ $event->target?->group?->name ?? '—' }}</td><th>Categoria</th><td>{{ $event->target?->category ?? '—' }}</td></tr>
<tr><th>RBL/lista</th><td>{{ $event->list?->name ?? '—' }}</td><th>IP individual afetado</th><td>{{ $event->last_checked_value ?? '—' }}</td></tr>
<tr><th>Primeira detecção</th><td>{{ $event->first_seen_at?->format('d/m/Y H:i:s') }}</td><th>Última detecção</th><td>{{ $event->last_seen_at?->format('d/m/Y H:i:s') }}</td></tr>
<tr><th>Resolução</th><td>{{ $event->resolved_at?->format('d/m/Y H:i:s') ?? '—' }}</td><th>Duração aproximada</th><td>{{ $event->durationMinutes() }} min</td></tr>
<tr><th>Última resposta</th><td>{{ $event->last_response ?? '—' }}</td><th>Último check relacionado</th><td>{{ $checks->last()?->checked_at?->format('d/m/Y H:i:s') ?? '—' }} {{ $checks->last()?->status }}</td></tr>
<tr><th>Alertas relacionados</th><td colspan="3">@include('rbl.alert-status')</td></tr>
</tbody></table></div></div>
<div class="panel"><h2>Investigação</h2><form method="POST" action="{{ route('rbl.events.investigation.update', $event) }}">@csrf @method('PATCH')<div class="form-grid"><div class="field-group"><label for="investigation_status">Classificação</label><select class="form-control" id="investigation_status" name="investigation_status"><option value="">Limpar classificação</option>@foreach(['pending' => 'Pendente', 'investigating' => 'Em investigação', 'investigated' => 'Investigado', 'false_positive' => 'Falso positivo'] as $value => $label)<option value="{{ $value }}" @selected(old('investigation_status', $event->investigation_status) === $value)>{{ $label }}</option>@endforeach</select></div><div class="field-group"><label for="operator_notes">Observações operacionais</label><textarea class="form-control" id="operator_notes" name="operator_notes" rows="5" maxlength="5000">{{ old('operator_notes', $event->operator_notes) }}</textarea>@error('operator_notes')<small>{{ $message }}</small>@enderror</div></div><button class="button button-primary">Atualizar investigação</button></form>@if($event->investigated_at)<p>Classificado em {{ $event->investigated_at->format('d/m/Y H:i:s') }} por {{ $event->investigator?->name ?? 'usuário removido' }}.</p>@endif</div>
<div class="panel"><h2>Reincidência</h2><p>Eventos anteriores do mesmo alvo + RBL: <strong>{{ $recurrence['target_count'] }}</strong>. @if($recurrence['checked_value_count'] !== null)Eventos anteriores do mesmo IP + RBL: <strong>{{ $recurrence['checked_value_count'] }}</strong>.@endif</p><p>Última ocorrência anterior: @if($recurrence['last_event']){{ $recurrence['last_event']->first_seen_at->format('d/m/Y H:i:s') }} (há {{ $recurrence['last_event']->first_seen_at->diffForHumans($event->first_seen_at, true) }})@else — @endif</p></div>
<div class="panel"><h2>Linha do tempo</h2><div class="table-responsive"><table class="data-table"><thead><tr><th>Data</th><th>Tipo</th><th>Registro</th></tr></thead><tbody>@foreach($timeline as $item)<tr><td>{{ $item['at']?->format('d/m/Y H:i:s') ?? '—' }}</td><td>{{ $item['type'] }}</td><td>{{ $item['description'] }}</td></tr>@endforeach</tbody></table></div></div>
<div class="panel"><h2>Checks relacionados</h2><div class="table-responsive"><table class="data-table"><thead><tr><th>Data</th><th>Valor</th><th>Status</th><th>Resposta</th></tr></thead><tbody>@forelse($checks as $check)<tr><td>{{ $check->checked_at?->format('d/m/Y H:i:s') }}</td><td>{{ $check->checked_value }}</td><td>{{ $check->status }}</td><td>{{ $check->response ?? '—' }}</td></tr>@empty<tr><td colspan="4">Nenhum check relacionado.</td></tr>@endforelse</tbody></table></div></div>
@endsection
