<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Relatório do evento RBL #{{ $event->id }}</title><style>body{font-family:sans-serif;max-width:1000px;margin:2rem auto;color:#222}table{border-collapse:collapse;width:100%;margin:1rem 0}th,td{border:1px solid #bbb;padding:.5rem;text-align:left;vertical-align:top}h1,h2{margin-top:1.5rem}@media print{button{display:none}}</style></head><body>
<button onclick="window.print()">Imprimir</button><h1>Relatório do incidente RBL #{{ $event->id }}</h1><p>Gerado em {{ $generatedAt->format('d/m/Y H:i:s') }} por {{ $generatedBy?->name ?? 'administrador' }}.</p>
<h2>Evento</h2><table><tbody><tr><th>Status técnico</th><td>{{ $event->status }}</td><th>Investigação</th><td>{{ $event->investigation_status ?? 'sem classificação' }}</td></tr><tr><th>Alvo</th><td>{{ $event->target?->name }} — {{ $event->target?->value }}</td><th>Grupo / categoria</th><td>{{ $event->target?->group?->name ?? '—' }} / {{ $event->target?->category ?? '—' }}</td></tr><tr><th>RBL</th><td>{{ $event->list?->name }}</td><th>IP afetado</th><td>{{ $event->last_checked_value ?? '—' }}</td></tr><tr><th>Primeira / última detecção</th><td>{{ $event->first_seen_at?->format('d/m/Y H:i:s') }} / {{ $event->last_seen_at?->format('d/m/Y H:i:s') }}</td><th>Resolução / duração</th><td>{{ $event->resolved_at?->format('d/m/Y H:i:s') ?? '—' }} / {{ $event->durationMinutes() }} min</td></tr><tr><th>Última resposta</th><td colspan="3">{{ $event->last_response ?? '—' }}</td></tr><tr><th>Observações operacionais</th><td colspan="3">{!! nl2br(e($event->operator_notes ?? '—')) !!}</td></tr></tbody></table>
<h2>Reincidência</h2><p>Mesmo alvo + RBL: {{ $recurrence['target_count'] }} ocorrência(s) anterior(es). @if($recurrence['checked_value_count'] !== null)Mesmo IP + RBL: {{ $recurrence['checked_value_count'] }}.@endif</p>
<h2>Delist assistido</h2><p>Orientação: {{ $event->list?->delist_instructions ?? 'Não cadastrada; revisar o fluxo oficial.' }}</p><table><tbody><tr><th>Status operacional</th><td>{{ $event->latestDelistRequest?->statusLabel() ?? 'Não solicitado' }}</td><th>Data da solicitação</th><td>{{ $event->latestDelistRequest?->requested_at?->format('d/m/Y H:i:s') ?? '—' }}</td></tr><tr><th>Protocolo</th><td>{{ $event->latestDelistRequest?->protocol ?? '—' }}</td><th>URL registrada</th><td>@if($event->latestDelistRequest?->request_url)<a href="{{ $event->latestDelistRequest->request_url }}" rel="noopener noreferrer">{{ $event->latestDelistRequest->request_url }}</a>@else — @endif</td></tr></tbody></table>
<h3>Histórico resumido de delist</h3><table><thead><tr><th>Registro</th><th>Status</th><th>Solicitado em</th><th>Protocolo</th><th>Responsável</th></tr></thead><tbody>@forelse($event->delistRequests as $item)<tr><td>{{ $item->created_at?->format('d/m/Y H:i:s') }}</td><td>{{ $item->statusLabel() }}</td><td>{{ $item->requested_at?->format('d/m/Y H:i:s') ?? '—' }}</td><td>{{ $item->protocol ?? '—' }}</td><td>{{ $item->user?->name ?? 'usuário removido' }}</td></tr>@empty<tr><td colspan="5">Nenhuma ação registrada.</td></tr>@endforelse</tbody></table>
<h2>Linha do tempo</h2><table><thead><tr><th>Data</th><th>Tipo</th><th>Registro</th></tr></thead><tbody>@foreach($timeline as $item)<tr><td>{{ $item['at']?->format('d/m/Y H:i:s') ?? '—' }}</td><td>{{ $item['type'] }}</td><td>{{ $item['description'] }}</td></tr>@endforeach</tbody></table>
<h2>Checks relacionados</h2><table><thead><tr><th>Data</th><th>Valor</th><th>Status</th><th>Resposta</th></tr></thead><tbody>@foreach($checks as $check)<tr><td>{{ $check->checked_at?->format('d/m/Y H:i:s') }}</td><td>{{ $check->checked_value }}</td><td>{{ $check->status }}</td><td>{{ $check->response ?? '—' }}</td></tr>@endforeach</tbody></table>
<h2>Alertas relacionados</h2><table><thead><tr><th>Data</th><th>Tipo</th><th>Canal</th><th>Status</th><th>Motivo</th></tr></thead><tbody>@forelse($event->alerts as $alert)<tr><td>{{ ($alert->sent_at ?? $alert->created_at)?->format('d/m/Y H:i:s') }}</td><td>{{ $alert->type }}</td><td>{{ $alert->channel }}</td><td>{{ $alert->status }}</td><td>{{ $alert->failure_reason ?? '—' }}</td></tr>@empty<tr><td colspan="5">Nenhum alerta relacionado.</td></tr>@endforelse</tbody></table>
</body></html>
