@if($compact ?? false)
<div class="table-responsive"><table class="data-table rbl-events-preview"><thead><tr><th>Alvo</th><th>IP listado</th><th>RBL</th><th>Status</th><th>Investigação</th><th>Delist</th><th>Última detecção</th><th>Ação</th></tr></thead><tbody>
@forelse($events as $event)
<tr><td>@if($event->target)<a href="{{ route('rbl.targets.show', $event->target) }}"><strong>{{ $event->target->name }}</strong></a>@else — @endif</td><td>{{ $event->last_checked_value ?? '—' }}</td><td>{{ $event->list?->name ?? '—' }}</td><td><span class="status-pill {{ $event->status === 'open' ? 'is-inactive' : 'is-active' }}">{{ $event->status === 'open' ? 'Aberto' : 'Resolvido' }}</span></td><td><span class="badge">{{ ['pending' => 'Pendente', 'investigating' => 'Em investigação', 'investigated' => 'Investigado', 'false_positive' => 'Falso positivo'][$event->investigation_status] ?? 'Sem classificação' }}</span></td><td><span class="badge">{{ \App\Models\RblDelistRequest::STATUS_LABELS[$event->latestDelistRequest?->status ?? 'not_requested'] }}</span></td><td>{{ $event->last_seen_at?->format('d/m/Y H:i') ?? '—' }}</td><td><a class="button button-small" href="{{ route('rbl.events.show', $event) }}">Detalhes</a></td></tr>
@empty<tr class="rbl-empty-row"><td colspan="8">Nenhum evento aberto no momento.</td></tr>@endforelse
</tbody></table></div>
@else
<div class="table-responsive"><table class="data-table"><thead><tr><th>Alvo</th><th>Grupo</th><th>Valor</th><th>IP listado</th><th>RBL</th><th>Status</th><th>Investigação</th><th>Delist</th><th>Primeira detecção</th><th>Última detecção</th><th>Resolução</th><th>Duração aproximada</th><th>Última resposta listed</th><th>Alertas</th><th>Ação</th></tr></thead><tbody>
@forelse($events as $event)
<tr><td>@if($event->target)<a href="{{ route('rbl.targets.show', $event->target) }}">{{ $event->target->name }}</a>@else — @endif</td><td>{{ $event->target?->group?->name ?? '—' }}</td><td>{{ $event->target?->value ?? '—' }}</td><td>{{ $event->last_checked_value ?? '—' }}</td><td>{{ $event->list?->name ?? '—' }}</td><td>{{ $event->status }}</td><td><span class="badge">{{ ['pending' => 'Pendente', 'investigating' => 'Em investigação', 'investigated' => 'Investigado', 'false_positive' => 'Falso positivo'][$event->investigation_status] ?? 'Sem classificação' }}</span></td><td><span class="badge">{{ \App\Models\RblDelistRequest::STATUS_LABELS[$event->latestDelistRequest?->status ?? 'not_requested'] }}</span></td><td>{{ $event->first_seen_at?->format('d/m/Y H:i:s') ?? '—' }}</td><td>{{ $event->last_seen_at?->format('d/m/Y H:i:s') ?? '—' }}</td><td>{{ $event->resolved_at?->format('d/m/Y H:i:s') ?? '—' }}</td><td>{{ $event->durationMinutes() }} min</td><td>{{ $event->last_response ?? '—' }}</td><td>@include('rbl.alert-status')</td><td><a class="button button-small" href="{{ route('rbl.events.show', $event) }}">Detalhes</a></td></tr>
@empty<tr><td colspan="15">Nenhum evento encontrado.</td></tr>@endforelse
</tbody></table></div>
@endif
