@extends('layouts.app')
@section('title', 'RBL Checker')
@section('content')
@php
    $statusLabels = ['partial' => 'Parcial', 'listed' => 'Listado', 'clean' => 'Limpo', 'error' => 'Erro', 'timeout' => 'Erro', 'skipped' => 'Ignorado', 'unchecked' => 'Não verificado'];
    $runStatusLabels = ['completed' => 'Concluída', 'failed' => 'Falhou', 'running' => 'Em execução'];
    $featuredGroup = $groups->first(fn ($group) => $group->category === 'cgnat' || strtolower($group->name) === 'cgnat') ?? $groups->first();
    $featuredTarget = $targets->getCollection()->first(fn ($target) => $target->type === 'cidr' && $target->rbl_target_group_id === $featuredGroup?->id);
    $featuredState = $featuredTarget?->scanState;
    $runDuration = $lastRun?->duration_ms !== null ? (int) ceil($lastRun->duration_ms / 1000) : null;
@endphp
<div class="rbl-dashboard">
<div class="page-heading"><div><div class="page-eyebrow">Monitoramento</div><h1>RBL Checker</h1><p>Visão operacional da reputação dos seus alvos nas listas DNSBL.</p></div><a class="button button-primary" href="{{ route('rbl.targets.create') }}">Novo alvo</a></div>
@include('rbl.navigation')

<section class="metrics-grid rbl-summary-grid" aria-label="Resumo do monitoramento">
@foreach(['Alvos monitorados' => $total, 'Listados agora' => $listed, 'Eventos abertos' => $open, 'Erros nas últimas 24h' => $errors24h] as $label => $value)
<div class="metric-card"><div class="metric-label">{{ $label }}</div><div class="metric-value">{{ $value }}</div></div>
@endforeach
<div class="metric-card rbl-run-card"><div class="metric-label">Última execução</div><div class="rbl-last-run"><div><span class="status-pill {{ match($lastRun?->status) { 'completed' => 'is-active', 'failed' => 'is-inactive', 'running' => 'is-info', default => 'is-muted' } }}">{{ $runStatusLabels[$lastRun?->status] ?? 'Nunca executada' }}</span>@if($lastRun)<time datetime="{{ $lastRun->started_at->toIso8601String() }}">{{ $lastRun->started_at->format('d/m/Y H:i') }}</time>@endif</div>@if($lastRun)<span>{{ $lastRun->targets_checked }} alvos · {{ $lastRun->checks_created }} checks@if($runDuration !== null) · {{ $runDuration }}s@endif</span>@if($lastRun->error_message)<small title="{{ $lastRun->error_message }}">Execução concluída com mensagem de erro</small>@endif @else<span>Nenhuma execução registrada</span>@endif</div></div>
</section>

@if($featuredGroup)
<section class="panel rbl-featured-group"><div class="panel-header"><div><div class="panel-eyebrow">Grupo em destaque</div><h2>{{ $featuredGroup->name }}</h2></div><span class="status-pill {{ $featuredGroup->enabled ? 'is-active' : 'is-muted' }}">{{ $featuredGroup->enabled ? 'Ativo' : 'Desativado' }}</span></div>
<div class="rbl-featured-stats"><div><span>Alvos</span><strong>{{ $featuredGroup->targets_count }}</strong></div><div><span>Listados agora</span><strong>{{ $featuredGroup->listed_count }}</strong></div><div><span>Eventos abertos</span><strong>{{ $featuredGroup->open_count }}</strong></div>
@if($featuredTarget && $featuredState)<div class="rbl-featured-progress"><div class="rbl-progress-label"><span>{{ $featuredTarget->name }} · {{ $featuredTarget->value }}</span><strong>{{ $featuredState->scanned_ips }}/{{ $featuredState->total_ips }} · {{ $featuredState->progressPercent() }}%</strong></div><div class="rbl-progress" role="progressbar" aria-valuenow="{{ $featuredState->progressPercent() }}" aria-valuemin="0" aria-valuemax="100"><span style="width: {{ min(100, $featuredState->progressPercent()) }}%"></span></div><small>Ciclo {{ $featuredState->cycle }} · P {{ $featuredState->pendingIps() }} · L {{ $featuredState->listed_ips }} · E {{ $featuredState->error_ips }}</small></div>@endif
</div><a class="rbl-section-link" href="{{ route('rbl.groups.show', $featuredGroup) }}">Ver grupo completo</a></section>
@endif

<section class="panel"><div class="panel-header"><div><div class="panel-eyebrow">Operação crítica</div><h2>Últimos eventos abertos</h2></div><a class="rbl-section-link" href="{{ route('rbl.events') }}">Ver todos os eventos</a></div>@include('rbl.event-table', ['events' => $openEvents, 'compact' => true])</section>

<section class="panel rbl-compact-panel"><div class="panel-header"><div><div class="panel-eyebrow">Saúde das consultas</div><h2>Últimos checks com erro ou timeout</h2></div></div><div class="table-responsive"><table class="data-table rbl-errors-table"><thead><tr><th>Alvo</th><th>Valor / IP</th><th>RBL</th><th>Status</th><th>Data</th><th>Erro</th></tr></thead><tbody>
@forelse($errorChecks as $check)<tr><td>{{ $check->target?->name ?? '—' }}</td><td>{{ $check->checked_value }}</td><td>{{ $check->list?->name ?? '—' }}</td><td><span class="status-pill is-inactive">{{ ucfirst($check->status) }}</span></td><td>{{ $check->checked_at?->format('d/m/Y H:i') }}</td><td class="rbl-error-message" title="{{ $check->error_message }}">{{ $check->error_message ?? '—' }}</td></tr>@empty<tr class="rbl-empty-row"><td colspan="6">Nenhum erro ou timeout recente.</td></tr>@endforelse
</tbody></table></div></section>

@if($resolvedEvents->isNotEmpty())<details class="panel rbl-collapsible-panel"><summary>Eventos resolvidos recentes <span class="status-pill is-muted">{{ $resolved24h }} nas últimas 24h</span></summary>@include('rbl.event-table', ['events' => $resolvedEvents, 'compact' => true])</details>@endif

<section class="panel" id="alvos"><div class="panel-header"><div><div class="panel-eyebrow">Inventário operacional</div><h2>Alvos</h2></div></div><form method="GET" class="rbl-filter-form">@include('rbl.group-filter')<button class="button" type="submit">Filtrar alvos</button></form><p class="rbl-section-note">O status reflete a última execução. Eventos permanecem abertos quando uma consulta falha ou é ignorada.</p><div class="table-responsive"><table class="data-table rbl-targets-table"><thead><tr><th>Nome</th><th>Tipo / valor</th><th>Grupo</th><th>Status</th><th>Progresso CIDR</th><th>Última verificação</th><th>Ações</th></tr></thead><tbody>
@forelse($targets as $target)<tr><td><a href="{{ route('rbl.targets.show', $target) }}"><strong>{{ $target->name }}</strong></a></td><td><span class="rbl-type-label">{{ strtoupper($target->type) }}</span><span class="rbl-target-value">{{ $target->value }}</span></td><td>{{ $target->group?->name ?? $target->category ?? '—' }} @if($target->type === 'cidr' && ($target->category === 'cgnat' || $target->group?->category === 'cgnat' || strtolower($target->group?->name ?? '') === 'cgnat'))<span class="status-pill is-info">CGNAT</span>@endif</td><td><strong>{{ $statusLabels[$target->last_status ?? 'unchecked'] ?? $target->last_status }}</strong>{{ $target->enabled ? '' : ' (desativado)' }}@if($target->type === 'cidr' && $target->last_status === 'partial')<small class="rbl-compact-note">ciclo em andamento</small>@endif</td><td>@if($target->type === 'cidr')@php($state = $target->scanState)<span class="rbl-compact-progress"><strong>{{ $state?->scanned_ips ?? 0 }}/{{ $state?->total_ips ?? $target->cidrTotalIps() }} ({{ $state?->progressPercent() ?? 0 }}%)</strong> · P {{ $state?->pendingIps() ?? $target->cidrTotalIps() }} · L {{ $state?->listed_ips ?? 0 }} · E {{ $state?->error_ips ?? 0 }} · ciclo {{ $state?->cycle ?? 0 }}</span>@else — @endif</td><td>{{ $target->last_checked_at?->format('d/m/Y H:i') ?? 'Nunca' }}</td><td><div class="rbl-table-actions">@if($target->enabled)<form method="POST" action="{{ route('rbl.targets.check', $target) }}">@csrf<button class="button button-primary button-small" type="submit">Verificar agora</button></form>@endif<a href="{{ route('rbl.targets.show', $target) }}">Histórico</a></div></td></tr>@empty<tr class="rbl-empty-row"><td colspan="7">Nenhum alvo cadastrado.</td></tr>@endforelse
</tbody></table></div>{{ $targets->links() }}@if($uncheckedTargets->isNotEmpty())<details class="rbl-unchecked"><summary>{{ $uncheckedTargets->count() }} alvo(s) ainda não verificado(s)</summary>@foreach($uncheckedTargets as $target)<a href="{{ route('rbl.targets.show', $target) }}">{{ $target->name }} · {{ $target->value }}</a>@endforeach</details>@endif</section>

<section class="rbl-settings" id="listas-rbl"><div class="rbl-settings-heading"><div><div class="panel-eyebrow">Configuração</div><h2>Listas RBL</h2></div><span>{{ $lists->where('enabled', true)->count() }} ativas de {{ $lists->count() }}</span></div>
<details class="panel rbl-collapsible-panel"><summary>Gerenciar listas RBL</summary><p class="rbl-section-note">Ative somente listas cujo uso foi autorizado pelo provedor. Limites: 1 verificação por alvo/minuto, {{ config('rbl.max_checks_per_target', 40) }} consultas e {{ config('rbl.max_seconds_per_target', 20) }} segundos de DNS por alvo.</p><div class="table-responsive"><table class="data-table"><thead><tr><th>Nome / descrição</th><th>Zona DNS</th><th>Tipo</th><th>Timeout</th><th>Estado</th><th>Ação</th></tr></thead><tbody>
@forelse($lists->sortByDesc('enabled') as $list)<tr><td><strong>{{ $list->name }}</strong><p class="rbl-list-description">{{ $list->description }}</p><details><summary>Orientação de delist</summary><form method="POST" action="{{ route('rbl.lists.guidance.update', $list) }}">@csrf @method('PATCH')<div class="field-group"><label for="lookup_url_{{ $list->id }}">URL de consulta</label><input class="form-control" id="lookup_url_{{ $list->id }}" name="lookup_url" type="url" maxlength="2048" value="{{ $list->lookup_url }}"></div><div class="field-group"><label for="delist_url_{{ $list->id }}">URL de solicitação</label><input class="form-control" id="delist_url_{{ $list->id }}" name="delist_url" type="url" maxlength="2048" value="{{ $list->delist_url }}"></div><div class="field-group"><label for="delist_instructions_{{ $list->id }}">Instruções</label><textarea class="form-control" id="delist_instructions_{{ $list->id }}" name="delist_instructions" maxlength="5000" rows="4">{{ $list->delist_instructions }}</textarea></div><input type="hidden" name="delist_requires_manual_review" value="0"><label><input type="checkbox" name="delist_requires_manual_review" value="1" @checked($list->delist_requires_manual_review)> Exige revisão manual</label><div><button class="button button-small" type="submit">Salvar orientação</button></div></form></details></td><td>{{ $list->dns_zone }}</td><td>{{ $list->type }}</td><td>{{ $list->timeout_seconds }}s</td><td><span class="status-pill {{ $list->enabled ? 'is-active' : 'is-muted' }}">{{ $list->enabled ? 'Ativa' : 'Desativada' }}</span></td><td><form method="POST" action="{{ route('rbl.lists.toggle', $list) }}">@csrf @method('PATCH')<button class="button {{ $list->enabled ? 'button-secondary' : 'rbl-button-positive' }}" type="submit">{{ $list->enabled ? 'Desativar' : 'Ativar' }}</button></form></td></tr>@empty<tr class="rbl-empty-row"><td colspan="6">Nenhuma lista cadastrada.</td></tr>@endforelse
</tbody></table></div></details>
<details class="panel form-panel rbl-list-registration" @if($errors->hasAny(['name', 'dns_zone', 'type', 'timeout_seconds', 'description'])) open @endif><summary>Cadastrar nova lista</summary><form method="POST" action="{{ route('rbl.lists.store') }}">@csrf<div class="form-grid">@foreach(['name' => 'Nome', 'dns_zone' => 'Zona DNS'] as $field => $label)<div class="field-group"><label for="list_{{ $field }}">{{ $label }}</label><input class="form-control" id="list_{{ $field }}" name="{{ $field }}" value="{{ old($field) }}" required></div>@endforeach<div class="field-group"><label for="list_type">Tipo</label><select class="form-control" id="list_type" name="type"><option value="ip" @selected(old('type') === 'ip')>IP</option><option value="domain" @selected(old('type') === 'domain')>Domínio (fase futura)</option></select></div><div class="field-group"><label for="timeout_seconds">Timeout (segundos)</label><input class="form-control" id="timeout_seconds" name="timeout_seconds" type="number" min="1" max="5" value="{{ old('timeout_seconds', 5) }}" required></div><div class="field-group"><label for="list_description">Descrição</label><textarea class="form-control" id="list_description" name="description" maxlength="2000">{{ old('description') }}</textarea></div></div><button class="button button-primary" type="submit">Cadastrar lista</button></form></details>
</section></div>
@endsection
