@extends('layouts.app')
@section('title', 'Relatório RBL')
@section('content')
@php($statusLabels = ['partial' => 'Parcial', 'listed' => 'Listado', 'clean' => 'Limpo', 'error' => 'Erro', 'timeout' => 'Erro', 'skipped' => 'Ignorado', 'unchecked' => 'Não verificado'])
<div class="page-heading"><div><div class="page-eyebrow">Monitoramento</div><h1>Relatório RBL</h1><p>Datas inclusivas no fuso {{ config('app.timezone') }}. Eventos abertos contabilizam primeiras detecções, mesmo que já resolvidos.</p></div></div>
@include('rbl.navigation')
<div class="panel"><h2>Alertas no período</h2><p>Contagem pela data de registro do alerta, com o filtro de grupo selecionado.</p><div class="metrics-grid">@foreach($alertSummary as $label => $value)<div class="metric-card"><div class="metric-label">{{ $label }}</div><div class="metric-value">{{ $value }}</div></div>@endforeach</div></div>
<div class="panel form-panel"><form method="GET" action="{{ route('rbl.reports') }}"><div class="form-grid">@include('rbl.period')</div><button class="button button-primary">Filtrar</button> <button class="button" name="format" value="csv">Exportar CSV</button></form></div>
<div class="metrics-grid">@foreach($summary as $label => $value)<div class="metric-card"><div class="metric-label">{{ $label }}</div><div class="metric-value">{{ $value }}</div></div>@endforeach</div>
<div class="panel"><h2>Resumo de blocos CIDR</h2><div class="metrics-grid">@foreach($blockSummary as $label => $value)<div class="metric-card"><div class="metric-label">{{ $label }}</div><div class="metric-value">{{ $value }}</div></div>@endforeach</div>
@foreach([['Blocos com mais IPs listados', $listedBlocks, 'listed_ips', 'Listados'], ['Blocos com mais IPs pendentes', $pendingBlocks, 'pending', 'Pendentes'], ['Blocos com erro', $errorBlocks, 'error_ips', 'Erros']] as [$title, $blocks, $field, $column])
<h3>{{ $title }}</h3><div class="table-responsive"><table class="data-table"><thead><tr><th>Grupo</th><th>Bloco</th><th>{{ $column }}</th><th>Progresso</th><th>Status agregado</th></tr></thead><tbody>@forelse($blocks as $block)<tr><td>{{ $block->group?->name ?? '—' }}</td><td><a href="{{ route('rbl.targets.show', $block) }}">{{ $block->value }}</a></td><td>{{ $field === 'pending' ? ($block->scanState?->pendingIps() ?? $block->cidrTotalIps()) : ($block->scanState?->{$field} ?? 0) }}</td><td>{{ $block->scanState?->progressPercent() ?? 0 }}%</td><td>{{ $statusLabels[$block->last_status ?? 'unchecked'] ?? $block->last_status }}</td></tr>@empty<tr><td colspan="5">Nenhum bloco nesta condição.</td></tr>@endforelse</tbody></table></div>
@endforeach
<h3>IPs individuais listados por bloco no período</h3><div class="table-responsive"><table class="data-table"><thead><tr><th>Grupo</th><th>Bloco</th><th>IP</th><th>RBL</th><th>Data</th></tr></thead><tbody>@forelse($listedBlockIps as $check)<tr><td>{{ $check->target?->group?->name ?? '—' }}</td><td>{{ $check->target?->value }}</td><td>{{ $check->checked_value }}</td><td>{{ $check->list?->name }}</td><td>{{ $check->checked_at?->format('d/m/Y H:i:s') }}</td></tr>@empty<tr><td colspan="5">Nenhum IP de bloco listado no período.</td></tr>@endforelse</tbody></table></div></div>
<div class="panel"><h2>Alvos mais recorrentes em blacklist</h2><p>Até 20 alvos, por quantidade de checks listed; um alvo pode aparecer em várias listas.</p><div class="table-responsive"><table class="data-table"><thead><tr><th>Alvo</th><th>Valor verificado</th><th>Ocorrências listed</th></tr></thead><tbody>@forelse($topTargets as $item)<tr><td>{{ $item->target?->name ?? '—' }}</td><td>{{ $item->checked_value }}</td><td>{{ $item->total }}</td></tr>@empty<tr><td colspan="3">Nenhuma ocorrência no período.</td></tr>@endforelse</tbody></table></div></div>
<div class="panel"><h2>RBLs com mais ocorrências</h2><p>Até 20 listas por quantidade de checks listed.</p><div class="table-responsive"><table class="data-table"><thead><tr><th>RBL</th><th>Ocorrências listed</th></tr></thead><tbody>@forelse($topLists as $item)<tr><td>{{ $item->list?->name ?? '—' }}</td><td>{{ $item->total }}</td></tr>@empty<tr><td colspan="2">Nenhuma ocorrência no período.</td></tr>@endforelse</tbody></table></div></div>
<div class="panel"><h2>Reincidências por eventos no período</h2><p>Contagens de eventos distintos, sem scoring.</p><div class="table-responsive"><table class="data-table"><thead><tr><th>Alvo</th><th>Eventos</th></tr></thead><tbody>@forelse($recurringTargets as $item)<tr><td>{{ $item->target?->name ?? '—' }}</td><td>{{ $item->total }}</td></tr>@empty<tr><td colspan="2">Nenhum alvo reincidente.</td></tr>@endforelse</tbody></table></div><div class="table-responsive"><table class="data-table"><thead><tr><th>IP individual</th><th>Eventos</th></tr></thead><tbody>@forelse($recurringValues as $item)<tr><td>{{ $item->last_checked_value }}</td><td>{{ $item->total }}</td></tr>@empty<tr><td colspan="2">Nenhum IP reincidente.</td></tr>@endforelse</tbody></table></div><div class="table-responsive"><table class="data-table"><thead><tr><th>RBL</th><th>Eventos</th></tr></thead><tbody>@forelse($eventLists as $item)<tr><td>{{ $item->list?->name ?? '—' }}</td><td>{{ $item->total }}</td></tr>@empty<tr><td colspan="2">Nenhum evento no período.</td></tr>@endforelse</tbody></table></div></div>
<div class="panel"><h2>Resumo por grupo</h2><div class="table-responsive"><table class="data-table">@foreach($groupSummary as $row)@if($loop->first)<thead><tr>@foreach(array_keys($row) as $label)<th>{{ $label }}</th>@endforeach</tr></thead><tbody>@endif<tr>@foreach($row as $value)<td>{{ $value }}</td>@endforeach</tr>@if($loop->last)</tbody>@endif
@endforeach</table></div></div>
@endsection
