@extends('layouts.app')
@section('title', $target->name.' — RBL Checker')
@section('content')
@php
    $statusLabels = ['partial' => 'Parcial', 'listed' => 'Listado', 'clean' => 'Limpo', 'error' => 'Erro', 'timeout' => 'Erro', 'skipped' => 'Ignorado', 'unchecked' => 'Não verificado'];
    $statusClasses = ['partial' => 'is-warning', 'listed' => 'is-inactive', 'clean' => 'is-active', 'error' => 'is-inactive', 'timeout' => 'is-inactive', 'skipped' => 'is-muted', 'unchecked' => 'is-muted'];
    $status = $target->last_status ?? 'unchecked';
    $totalIps = $scanState?->total_ips ?? $target->cidrTotalIps();
    $progress = $scanState?->progressPercent() ?? 0;
@endphp
<div class="rbl-dashboard">
<div class="page-heading"><h1>{{ $target->name }}</h1><a href="{{ route('rbl.index') }}">Voltar ao RBL Checker</a></div>
<div class="panel"><h2>Dados do alvo</h2><p>Grupo: {{ $target->group?->name ?? '—' }}</p><a class="button" href="{{ route('rbl.targets.edit', $target) }}">Editar alvo</a><p>{{ strtoupper($target->type) }}: {{ $target->value }} · Categoria: {{ $target->category ?? '—' }} · {{ $target->enabled ? 'Ativo' : 'Desativado' }}</p><p>{{ $target->description }}</p><p>Resultado da última verificação: <span class="status-pill {{ $statusClasses[$status] ?? 'is-muted' }}">{{ $statusLabels[$status] ?? $status }}</span> · {{ $target->last_checked_at?->format('d/m/Y H:i:s') ?? 'Nunca' }}</p>
@if($target->type === 'cidr')<p class="rbl-status-explanation">@switch($status) @case('partial') Ciclo ainda não concluído. @break @case('listed') Há pelo menos um IP com evento aberto. @break @case('clean') Ciclo completo sem listagens abertas. @break @case('error') O ciclo completo contém IPs com erro ou timeout. @break @case('skipped') O ciclo contém consultas ignoradas. @break @default A varredura ainda não começou. @endswitch</p>@endif
<div class="rbl-actions">@if($target->enabled)<form method="POST" action="{{ route('rbl.targets.check', $target) }}">@csrf<button class="button button-primary" type="submit">Verificar agora — próximo lote</button></form>@endif<form method="POST" action="{{ route('rbl.targets.toggle', $target) }}">@csrf @method('PATCH')<button class="button" type="submit">{{ $target->enabled ? 'Desativar alvo' : 'Ativar alvo' }}</button></form></div></div>

@if($target->type === 'cidr')
<section class="panel" aria-labelledby="cgnat-progress-title"><div class="panel-header"><div><div class="page-eyebrow">Varredura incremental</div><h2 id="cgnat-progress-title">Progresso do bloco CGNAT</h2></div><span class="status-pill is-info">CGNAT</span></div>
<p>Este bloco é verificado em lotes para evitar excesso de consultas em RBLs. Enquanto o ciclo não termina, o status pode permanecer Parcial.</p>
<div class="rbl-scan-grid"><div><span>CIDR monitorado</span><strong>{{ $target->value }}</strong></div><div><span>Total de IPs</span><strong>{{ $totalIps }}</strong></div><div><span>Ciclo atual</span><strong>{{ $scanState?->cycle ?? 0 }}</strong></div><div><span>Cursor atual</span><strong>{{ $scanState?->cursor ?? 0 }}</strong></div><div><span>Verificados no ciclo</span><strong>{{ $scanState?->scanned_ips ?? 0 }}</strong></div><div><span>Pendentes estimados</span><strong>{{ $scanState?->pendingIps() ?? $totalIps }}</strong></div><div><span>IPs listados</span><strong>{{ $scanState?->listed_ips ?? 0 }}</strong></div><div><span>IPs limpos</span><strong>{{ $scanState?->clean_ips ?? 0 }}</strong></div><div><span>Erros / timeout</span><strong>{{ $scanState?->error_ips ?? 0 }}</strong></div><div><span>Ignorados</span><strong>{{ $scanState?->skipped_ips ?? 0 }}</strong></div><div><span>Última verificação</span><strong>{{ $scanState?->last_checked_at?->format('d/m/Y H:i:s') ?? 'Nunca' }}</strong></div></div>
<div class="rbl-progress-label"><strong>Progresso do ciclo</strong><span>{{ number_format($progress, 1, ',', '.') }}%</span></div><div class="rbl-progress" role="progressbar" aria-label="Progresso do ciclo do bloco" aria-valuemin="0" aria-valuemax="100" aria-valuenow="{{ $progress }}"><span style="width: {{ min(100, max(0, $progress)) }}%"></span></div>
<div class="rbl-next-batch"><h3>Próximo lote planejado</h3>@if($nextBatch && !$nextBatch['reason'])<p><strong>{{ count($nextBatch['ips']) }} IPs</strong> · {{ $activeLists }} listas ativas ({{ $activeIpLists }} para IP) · <strong>{{ min($maxChecks, count($nextBatch['ips']) * $activeIpLists) }} checks planejados</strong> · limite de {{ $maxChecks }} consultas por alvo preservado</p>@if($nextBatch['ips'])<p class="rbl-ip-preview">Próximos IPs (máximo 16): {{ implode(', ', array_slice($nextBatch['ips'], 0, 16)) }}</p>@endif @else<p>{{ $nextBatch['reason'] ?? 'Não foi possível estimar o lote.' }}</p>@endif</div></section>
<div class="panel"><h2>IPs listados neste bloco</h2><p>Eventos abertos, ordenados pela detecção mais recente.</p><div class="table-responsive"><table class="data-table"><thead><tr><th>IP listado</th><th>RBL</th><th>Primeira detecção</th><th>Última detecção</th><th>Resposta</th><th>Investigação</th><th>Ação</th></tr></thead><tbody>
@forelse($openEvents as $event)<tr><td>{{ $event->last_checked_value ?? '—' }}</td><td>{{ $event->list?->name ?? '—' }}</td><td>{{ $event->first_seen_at?->format('d/m/Y H:i:s') }}</td><td>{{ $event->last_seen_at?->format('d/m/Y H:i:s') }}</td><td>{{ $event->last_response ?? '—' }}</td><td>{{ ['pending' => 'Pendente', 'investigating' => 'Em investigação', 'investigated' => 'Investigado', 'false_positive' => 'Falso positivo'][$event->investigation_status] ?? 'Não classificado' }}</td><td><a href="{{ route('rbl.events.show', $event) }}">Ver evento</a></td></tr>@empty<tr><td colspan="7">Nenhum IP com evento aberto neste bloco.</td></tr>@endforelse
</tbody></table></div></div>
@endif

<div class="panel"><h2>{{ $target->type === 'cidr' ? 'Últimos IPs verificados' : 'Histórico de checks' }}</h2><p>Até 25 registros por página, do mais recente para o mais antigo.</p><div class="table-responsive"><table class="data-table"><thead><tr><th>Data</th><th>IP / valor verificado</th><th>RBL</th><th>Status</th><th>Resposta / erro</th></tr></thead><tbody>
@forelse($checks as $check)<tr><td>{{ $check->checked_at->format('d/m/Y H:i:s') }}</td><td>{{ $check->checked_value }}<p>{{ $check->query ?? '—' }}</p></td><td>{{ $check->list->name }}</td><td>{{ $statusLabels[$check->status] ?? $check->status }}</td><td>{{ $check->response ?? '—' }}<p>{{ $check->response_text }}</p><p>{{ $check->error_message }}</p></td></tr>@empty<tr><td colspan="5">Nenhuma verificação registrada.</td></tr>@endforelse
</tbody></table></div>{{ $checks->withQueryString()->links() }}</div>
<div class="panel"><h2>Histórico de eventos por IP</h2><div class="table-responsive"><table class="data-table"><thead><tr><th>RBL</th><th>IP individual</th><th>Status</th><th>Primeira ocorrência</th><th>Última ocorrência</th><th>Resolvido em</th><th>Resposta / notas</th></tr></thead><tbody>
@forelse($events as $event)<tr><td>{{ $event->list->name }}</td><td>{{ $event->last_checked_value ?? '—' }}</td><td>{{ $event->status === 'open' ? 'Aberto (open)' : 'Resolvido (resolved)' }}</td><td>{{ $event->first_seen_at->format('d/m/Y H:i:s') }}</td><td>{{ $event->last_seen_at->format('d/m/Y H:i:s') }}</td><td>{{ $event->resolved_at?->format('d/m/Y H:i:s') ?? '—' }}</td><td>{{ $event->last_response }}<p>{{ $event->notes }}</p></td></tr>@empty<tr><td colspan="7">Nenhum evento registrado.</td></tr>@endforelse
</tbody></table></div>{{ $events->withQueryString()->links() }}</div>
</div>
@endsection
