<?php
namespace App\Http\Controllers;
use App\Jobs\ProcessAnatelImport; use App\Models\AnatelImport; use App\Models\AuditLog; use App\Models\Lista;
use Illuminate\Http\JsonResponse; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Validation\ValidationException; use Illuminate\View\View;
class AnatelDashboardController extends Controller {
 public function index():View{$listas=Lista::where('origem','anatel')->withCount(['dominios as dominios_ativos_count'=>fn($q)=>$q->where('ativo',true),'servidores'])->orderBy('nome')->get();$imports=AnatelImport::with(['lista'=>fn($q)=>$q->withCount(['dominios as dominios_ativos_count'=>fn($d)=>$d->where('ativo',true)])])->latest()->limit(20)->get();return view('anatel.index',compact('listas','imports'));}
 public function store(Request $request):RedirectResponse{
  $data=$request->validate(['lista_id'=>['required','exists:listas,id'],'pdfs'=>['required','array','min:1','max:'.config('anatel.max_files')],'pdfs.*'=>['required','file','mimetypes:application/pdf,application/x-pdf','max:'.config('anatel.max_pdf_kb')]]);$lista=Lista::findOrFail($data['lista_id']);abort_unless($lista->isAnatel(),422);$ids=[];
  foreach($request->file('pdfs')as$upload){$real=$upload->getRealPath();if(!$real||file_get_contents($real,false,null,0,5)!=='%PDF-')throw ValidationException::withMessages(['pdfs'=>'O conteúdo enviado não é um PDF válido.']);$sha=hash_file('sha256',$real);if(AnatelImport::where('sha256',$sha)->whereIn('status',['pending','processing','completed'])->exists())throw ValidationException::withMessages(['pdfs'=>'Um dos PDFs já foi processado.']);$path=$upload->storeAs(date('Y/m'),$sha.'.pdf','anatel');$import=AnatelImport::create(['lista_id'=>$lista->id,'user_id'=>$request->user()->id,'original_filename'=>basename($upload->getClientOriginalName()),'storage_path'=>$path,'sha256'=>$sha,'size_bytes'=>$upload->getSize(),'status'=>'pending','progress'=>0]);AuditLog::record('anatel.import.started','Importação ANATEL enfileirada: '.$import->original_filename,$lista->empresa_id,'anatel_import',$import->id);ProcessAnatelImport::dispatch($import->id);$ids[]=$import->id;}
  return redirect()->route('anatel.dashboard',['watch'=>implode(',',$ids)])->with('status','PDF(s) recebido(s). Processamento iniciado.');
 }
 public function status(AnatelImport $import):JsonResponse{$import->load('lista');return response()->json(['id'=>$import->id,'status'=>$import->status,'progress'=>$import->progress,'filename'=>$import->original_filename,'finished_at'=>optional($import->finished_at)->format('d/m/Y H:i:s'),'new'=>$import->new_count,'existing'=>$import->existing_count,'reactivated'=>$import->reactivated_count,'excluded'=>$import->excluded_count,'invalid'=>$import->invalid_count,'total_active'=>$import->lista->dominios()->where('ativo',true)->count(),'endpoints'=>$import->lista->servidores()->count(),'new_url'=>$import->status==='completed'?route('anatel.imports.new',[$import->lista,$import]):null]);}
}
